version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro 
    environment:
      - TRUST_DOWNSTREAM_PROXY=false  # Configuración para desconfiar del proxy aguas abajo. Ajusta según necesidades.
      - DEFAULT_HOST=ax01.dev
  www:
    image: nginx:latest
    restart: always
    expose:
      - "80"
    volumes:
      - /home/billy/ax01/client/build:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=ax01.dev,www.ax01.dev

volumes:
  certs:        
