version: '3'

services:
  
  nodeserver:
    build:
      context: ./server
    ports:
      - "3001:3001"
 
  nginx:
    image: nginx:alpine 
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/default.conf

